apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
    version: "4.7.0"
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: wazuh-agent
      hostNetwork: true
      hostPID: true
      hostIPC: true

      # Tolerations to run on all nodes including control plane
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoSchedule
          key: node-role.kubernetes.io/master

      containers:
        - name: wazuh-agent
          image: wazuh/wazuh-agent:4.7.0
          env:
            # Wazuh Manager connection details
            - name: WAZUH_MANAGER
              value: "wazuh-manager.wazuh.svc.cluster.local"  # Update with your Wazuh manager address
            - name: WAZUH_MANAGER_PORT
              value: "1514"
            - name: WAZUH_PROTOCOL
              value: "tcp"
            - name: WAZUH_REGISTRATION_SERVER
              value: "wazuh-manager.wazuh.svc.cluster.local"
            - name: WAZUH_REGISTRATION_PORT
              value: "1515"
            - name: WAZUH_REGISTRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-agent-password
                  key: password
            - name: WAZUH_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_AGENT_GROUP
              value: "kubernetes"

          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RESOURCE
                - SYS_PTRACE
                - AUDIT_CONTROL

          volumeMounts:
            # Host filesystem access for monitoring
            - name: rootfs
              mountPath: /host
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: etc
              mountPath: /host/etc
              readOnly: true
            - name: dev
              mountPath: /host/dev
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: boot
              mountPath: /host/boot
              readOnly: true
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: wazuh-config
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: etc
          hostPath:
            path: /etc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: boot
          hostPath:
            path: /boot
        - name: modules
          hostPath:
            path: /lib/modules
        - name: wazuh-config
          configMap:
            name: wazuh-agent-config
