---
apiVersion: v1
kind: Namespace
metadata:
  name: wazuh
  labels:
    name: wazuh

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wazuh-agent
  labels:
    app: wazuh-agent
rules:
  # Get pods for monitoring
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - services
      - endpoints
    verbs: ["get", "list", "watch"]

  # Get events for security monitoring
  - apiGroups: [""]
    resources:
      - events
    verbs: ["get", "list", "watch"]

  # Get deployments and replicasets
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]

  # Get jobs and cronjobs
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-agent
  labels:
    app: wazuh-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wazuh-agent
subjects:
  - kind: ServiceAccount
    name: wazuh-agent
    namespace: wazuh

---
# Secret for Wazuh agent registration password
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-agent-password
  namespace: wazuh
type: Opaque
stringData:
  # Change this password to match your Wazuh manager configuration
  password: "ChangeMe123!"
